version: '3.8'

services:
  web:
    environment:
      - FLASK_ENV=development
    volumes:
      - ./certificate.pem:/certificate.pem
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    volumes:
      - redis-data:/data

volumes:
  redis-data:
