version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ["web"]
    labels:
      heroku.process.type: "web"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}  # Use the Heroku-provided Redis URL
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - PYTHONPATH=./app
    volumes:
      - ./certificate.pem:/certificate.pem:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    ports:
      - "80:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: ["worker"]
    labels:
      heroku.process.type: "worker"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}  # Use the Heroku-provided Redis URL
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - SSL_CERT_PATH=/certificate.pem
      - PYTHONPATH=./app
    volumes:
      - ./certificate.pem:/certificate.pem:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: "256M"
