version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ["web"]  # Matches the 'web' case in your entrypoint script
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=production
      - PYTHONPATH=./app
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: ["worker"]  # Matches the 'worker' case in your entrypoint script
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - FLASK_ENV=production
      - PYTHONPATH=./app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
