version: '3.8'

services:
  web:
    build:
      context: .
    command: ["web"]
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    ports:
      - "80:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .
    command: ["worker"]

    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: "256M"
    depends_on:
      - redis

volumes:
  redis-data:
