services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ["web"]
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret
      - DATABASE_URL=postgres://u5n1r0okqlgr9m:p504d2830a6b63d716424a472a3f28685b558272982eede6e3d8752e511f3afe8@cd1goc44htrmfn.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d307p6e4nkqktl
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: ["worker"]
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret
      - DATABASE_URL=postgres://u5n1r0okqlgr9m:p504d2830a6b63d716424a472a3f28685b558272982eede6e3d8752e511f3afe8@cd1goc44htrmfn.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d307p6e4nkqktl
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
