version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key
      - DATABASE_URL=sqlite:///site.db
      - REDIS_URL=redis://redis:6379/0
      - PORT=8000
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
